### ISSUE TITLE
  Failed to run the last command, "P*SigA*(Q.T)", listed in `worksheet-svd.ipynb`.

### ISSUE THREAD

**Issue by hongyi-zhao** [sean-fitzpatrick/3410worksheets#1]
I try to run all the commands given in the notebook [worksheet-svd.ipynb](https://github.com/sean-fitzpatrick/3410worksheets/blob/main/worksheet-svd.ipynb), but the last command given there failed as shown below:

```
In [154]: P
Out[154]: 
⎡ √2   √2⎤
⎢ ──   ──⎥
⎢ 2    2 ⎥
⎢        ⎥
⎢-√2   √2⎥
⎢────  ──⎥
⎣ 2    2 ⎦

In [155]: SigA
Out[155]: 
⎡√3        0         0⎤
⎢                     ⎥
⎢    ⎛      ⎡⎡1 ⎤⎤⎞   ⎥
⎢    ⎜      ⎢⎢  ⎥⎥⎟   ⎥
⎢    ⎜      ⎢⎢-1⎥⎥⎟   ⎥
⎢0   ⎜0, 1, ⎢⎢  ⎥⎥⎟  0⎥
⎢    ⎜      ⎢⎢-1⎥⎥⎟   ⎥
⎢    ⎜      ⎢⎢  ⎥⎥⎟   ⎥
⎣    ⎝      ⎣⎣1 ⎦⎦⎠   ⎦

In [156]: Q.T
Out[156]: 
⎡ √6   -√6   √6⎤
⎢ ──   ────  ──⎥
⎢ 3     6    6 ⎥
⎢              ⎥
⎢       √2   √2⎥
⎢ 0     ──   ──⎥
⎢       2    2 ⎥
⎢              ⎥
⎢-√3   -√3   √3⎥
⎢────  ────  ──⎥
⎣ 3     3    3 ⎦

In [157]: P*SigA*(Q.T)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/.pyenv/versions/3.9.0/envs/datasci/lib/python3.9/site-packages/sympy/core/compatibility.py in as_int(n, strict)
    300                 raise TypeError
--> 301             return operator.index(n)
    302         except TypeError:

TypeError: 'Mul' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
~/.pyenv/versions/3.9.0/envs/datasci/lib/python3.9/site-packages/sympy/core/containers.py in __mul__(self, other)
     87         try:
---> 88             n = as_int(other)
     89         except ValueError:

~/.pyenv/versions/3.9.0/envs/datasci/lib/python3.9/site-packages/sympy/core/compatibility.py in as_int(n, strict)
    302         except TypeError:
--> 303             raise ValueError('%s is not an integer' % (n,))
    304     else:

ValueError: sqrt(2)/2 is not an integer

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
<ipython-input-157-e52f404c7f29> in <module>
----> 1 P*SigA*(Q.T)

~/.pyenv/versions/3.9.0/envs/datasci/lib/python3.9/site-packages/sympy/core/decorators.py in binary_op_wrapper(self, other)
    134                     if f is not None:
    135                         return f(self)
--> 136             return func(self, other)
    137         return binary_op_wrapper
    138     return priority_decorator

~/.pyenv/versions/3.9.0/envs/datasci/lib/python3.9/site-packages/sympy/matrices/common.py in __mul__(self, other)
   2740         """
   2741 
-> 2742         return self.multiply(other)
   2743 
   2744     def multiply(self, other, dotprodsimp=None):

~/.pyenv/versions/3.9.0/envs/datasci/lib/python3.9/site-packages/sympy/matrices/common.py in multiply(self, other, dotprodsimp)
   2767         # honest sympy matrices defer to their class's routine
   2768         if getattr(other, 'is_Matrix', False):
-> 2769             m = self._eval_matrix_mul(other)
   2770             if isimpbool:
   2771                 return m._new(m.rows, m.cols, [_dotprodsimp(e) for e in m])

~/.pyenv/versions/3.9.0/envs/datasci/lib/python3.9/site-packages/sympy/matrices/dense.py in _eval_matrix_mul(self, other)
    159                 row_indices = range(self_cols*row, self_cols*(row+1))
    160                 col_indices = range(col, other_len, other.cols)
--> 161                 vec = [mat[a]*other_mat[b] for a, b in zip(row_indices, col_indices)]
    162                 try:
    163                     new_mat[i] = Add(*vec)

~/.pyenv/versions/3.9.0/envs/datasci/lib/python3.9/site-packages/sympy/matrices/dense.py in <listcomp>(.0)
    159                 row_indices = range(self_cols*row, self_cols*(row+1))
    160                 col_indices = range(col, other_len, other.cols)
--> 161                 vec = [mat[a]*other_mat[b] for a, b in zip(row_indices, col_indices)]
    162                 try:
    163                     new_mat[i] = Add(*vec)

~/.pyenv/versions/3.9.0/envs/datasci/lib/python3.9/site-packages/sympy/core/containers.py in __mul__(self, other)
     88             n = as_int(other)
     89         except ValueError:
---> 90             raise TypeError("Can't multiply sequence by non-integer of type '%s'" % type(other))
     91         return self.func(*(self.args*n))
     92 

TypeError: Can't multiply sequence by non-integer of type '<class 'sympy.core.mul.Mul'>'

In [158]: 
```

Regards,
HY

**Comment by sean-fitzpatrick** [comment]
There is a typo in the definition of the matrix `SigA`:

`SigA = Matrix([[L0[0],0,0],[0,L[1],0])`

should be

`SigA = Matrix([[L0[0],0,0],[0,L0[1],0]])`.

 This is fixed in source, and in the HTML text. I didn't get around to updating the jupyter notebooks here.

Note that the only reason I maintain this repository is for teaching: it allows me to provide students with nbgitpuller links that open the notebooks on a Jupyter Hub. I do not assume students know Python, or have it installed on their computers. They only need to click a link to run it in a web browser.

The last command executes fine for me once I fix the typo as above:

![2021-05-26_14-42](https://user-images.githubusercontent.com/16246721/119729160-8fca3200-be31-11eb-9368-33c7b2f0c7a4.png)

The code also works on SageCell.

**Comment by hongyi-zhao** [comment]
> This is fixed in source, and in the HTML text. I didn't get around to updating the jupyter notebooks here.

I noticed the fixed HTML webpage [here](https://opentext.uleth.ca/Math3410/worksheet-svd.html). But it still hasn't been fixed [here](https://github.com/sean-fitzpatrick/Math3410/blob/1f3f4aeb9aae5b29a2efd7deb60aab8cc5f0e2a8/ptx/worksheet-svd.ptx#L105) in the corresponding pretext file. Where is the source code? It seems that it is not maintained as a GitHub repo.

**Comment by sean-fitzpatrick** [comment]
Sorry, what do you mean by source code?
The HTML is built from PreTeXt source. You have forked my GitHub repo with the PreTeXt source, so I would think you already know where to find it?

**Comment by sean-fitzpatrick** [comment]
Probably I have some uncommitted change in my local PreTeXt source. The semester in which I was teaching from this book is over, so this is not a high priority.

It'll get fixed at some point in the future when I have time.

I am one person, with primary job as a university instructor. I'm not a publishing company and I'm not charging you to access my course materials. If you're not satisfied with the "product" you are free to look elsewhere.

**Comment by hongyi-zhao** [comment]
> Sorry, what do you mean by source code?

Presumably, I misunderstand your meaning of `source`. Now, I see, you mean [the PreTeXt source](https://github.com/sean-fitzpatrick/Math3410) corresponding to this book.

> I'm not a publishing company and I'm not charging you to access my course materials. If you're not satisfied with the "product" you are free to look elsewhere.

I'm sorry to bother you and take up your time. Thank you again.

**Comment by sean-fitzpatrick** [comment]
Sorry for the overly grouchy response -- too many things needed to get done yesterday.
But I think maybe you are looking for a level of service I'm not able to provide.

If you find mistakes (typos, coding errors, etc) feel free to let me know, but don't expect immediate fixes. (Pull requests are welcome if you fix it yourself.)
For help learning PreTeXt, you are better off going to [the website](https://pretextbook.org/) to access the guide or the forums. Maybe one day I'll figure out how to provide a makefile, but (a) that's not any time soon, and (b) it would still require some familiarity with PreTeXt.

I had time this morning to push typo changes that I had locally. If you update your fork you should get the corrections.

**Comment by hongyi-zhao** [comment]
> Sorry for the overly grouchy response -- too many things needed to get done yesterday.

You're welcome.

> But I think maybe you are looking for a level of service I'm not able to provide.

Of course not. We all use the free service of GitHub, so this is just a free communication, free as in freedom.
